<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>PulseBus</PackageId>
    <Version>1.1.0</Version>
    <Authors>Andrés Mariño</Authors>
    <Company>PulseBus</Company>
    <Description>PulseBus is a minimalistic, extensible, provider-agnostic messaging abstraction for .NET. Designed for RabbitMQ, Azure Queue, AWS SQS, Kafka and more.</Description>
    <PackageTags>messaging;bus;queue;event-driven;microservices;rabbitmq;sqs;kafka;azure</PackageTags>
    <RepositoryUrl>https://github.com/ffamaximus/PulseBus</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>Icon.PNG</PackageIcon>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\Icon.PNG" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
  </ItemGroup>

</Project>
